name: Run tests for API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - './**'  
env:
  DB_USERNAME: ${{secrets.DB_USERNAME}}
  DB_PASSWORD: ${{secrets.DB_PASSWORD}}
  DB_HOST: ${{secrets.DB_HOST}}
  DB_DIALECT: ${{secrets.DB_DIALECT}}
  DB_STORAGE: ${{secrets.DB_STORAGE}}

jobs:
  run_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    environment: .env.test

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    
    - name: Run Tests
      run: |
        npm install
        npm run test
